### ISSUE TITLE
how can we run same test multiple times?

### ISSUE THREAD

**Issue by mboussaa** [haxe-utest/utest#30]
how can we run same test multiple times?

**Comment by romanmikhailov** [comment]
Hi @mboussaa 
What do you mean under "how can we run same test multiple times"?
Can you provide an example?

**Comment by RealyUniqueName** [comment]
You can make it an ordinary function and call it as many times as you wish. E.g. create multiple test functions `testMyFunc1, testMyFunc2, testMyFun3` which will call `myFunc()`.
However i think running the same test multiple times is pointless, because your test should not depend on a global state changing over time.
Feel free to reopen if you have more details.
